image: atlassian/default-image:2

clone:
  depth: full

definitions:
  steps:
    - step: &build-step
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
              SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
              SONAR_EXCLUDE: node_modules, android, ios
  caches:
    sonar: ~/.sonar

pipelines:
  branches:
    '{master,develop}': 
      - step: *build-step

  pull-requests:
    '**':
      - step:
          name: SonarQube analysis
          caches:
            - sonar
          script:
            - pipe: sonarsource/sonarqube-scan:1.0.0
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
                SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
                SONAR_EXCLUDE: node_modules, android, ios


