const WIDTH_BUTTON = '100%';
const TYPE_STYLE_BUTTON = 'primary';
const FILL_DEFAULT = 'none';
const STROKE_COLOR_DEFAULT = 'black';
const STROKE_WIDTH_DEFAULT = 1;
const SAVE_BUTTON_LABEL_DEFAULT = 'Save';
const CLEAR_BUTTON_LABEL_DEFAULT = 'Clear';
const SAVE_FORMAT_DEFAULT = 'base64';
const SAVE_HEIGHT_SVG_DEFAULT = 300;
const SAVE_WIDTH_SVG_DEFAULT = 400;
const SVG_XMLNS = 'http://www.w3.org/2000/svg';
const SVG_FOOTER = '</svg>';
const SVG_BASE64_PREFIX = 'data:image/svg+xml;base64';

export {
  WIDTH_BUTTON,
  TYPE_STYLE_BUTTON,
  FILL_DEFAULT,
  STROKE_COLOR_DEFAULT,
  STROKE_WIDTH_DEFAULT,
  SAVE_BUTTON_LABEL_DEFAULT,
  CLEAR_BUTTON_LABEL_DEFAULT,
  SAVE_FORMAT_DEFAULT,
  SAVE_HEIGHT_SVG_DEFAULT,
  SAVE_WIDTH_SVG_DEFAULT,
  SVG_XMLNS,
  SVG_FOOTER,
  SVG_BASE64_PREFIX,
};
