import {StyleSheet} from 'react-native';
import {
  BLACK,
  BLACK_TRANSPARENT,
  BLUE,
  BLUE_30,
  BLUE_40,
  BLUE_50,
  BLUE_80,
  GREY_10,
  GREY_40,
  GREY_5,
  GREY_BLUE,
  GREY_BLUE_30,
  GREY_BLUE_50,
  PURPLE_50,
  WHITE,
  YELLOW,
} from '../../../styles/colors';
import {CardStyleVariant} from './CardDropdown.types';

export const styles = StyleSheet.create({
  cardContainer: {
    width: 272,
    height: 168,
    borderRadius: 16,
    padding: 24,
    paddingRight: 23,
    display: 'flex',
    justifyContent: 'space-between',
  },
  cardImageContainer: {
    width: 68,
    height: 68,
    borderRadius: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImage: {
    width: 40,
    height: 40,
  },
  cardArrowImage: {
    height: 12,
    width: 12,
    marginRight: 10,
  },
  cardTitle: {
    fontSize: 22,
    width: 189,
  },
  cardDropdownContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  storiesContainer: {},
  cardOptionContainer: {
    width: 272,
    maxHeight: 442,
    minHeight: 168,
    borderRadius: 16,
    overflow: 'hidden',
    display: 'flex',
  },
  cardOptionHeader: {
    height: 58,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
  },
  cardOptionHeaderSkeletonLeftContainer: {
    flexDirection: 'row',
  },
  cardOptionHeaderTitle: {
    fontWeight: '500',
    fontSize: 16,
    width: 170,
    alignItems: 'center',
    display: 'flex',
  },
  cardOptionHeaderImage: {
    height: 20,
    width: 21,
    marginRight: 12,
  },
  cardOptionHeaderUp: {
    height: 12,
    width: 12,
  },
  cardHeaderLeftPart: {
    display: 'flex',
    flexDirection: 'row',
  },
  cardItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 86,
    borderBottomWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardLastItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0,
    minHeight: 86,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardOneItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 118,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardItemImageContainer: {
    width: 46,
    height: 46,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderRadius: 50,
  },
  cardItemImageCenter: {
    width: 24,
    height: 24,
    position: 'absolute',
  },
  cardImageCircle: {
    width: 52,
    height: 52,
  },
  cardItemTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  cardItemDescription: {
    fontSize: 14,
    fontWeight: '500',
  },
  overlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: BLACK_TRANSPARENT,
    zIndex: -1,
  },
  cardOptionSkeletonContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
  },
  cardOptionSkeletonRightContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginLeft: 12,
  },
  cardOptionSeparation: {
    height: 4,
  },
  cardOptionHeaderImg: {
    width: 24,
    height: 24,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardOptionHeaderImagenSize: {
    width: 24,
    height: 24,
  },
  cardOptionImagenSize: {
    width: 27,
    height: 27,
  },
  cardOptionArrowImage: {
    height: 12,
    width: 12,
    transform: [{rotate: '180deg'}],
  },
  cardItemTextContainer: {
    flex: 1,
  },
  cardOptionArrowContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 21,
  },
  cardDropdownStoriesRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  cardDropdownStoriesSkeletonContainer: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    height: 168,
    overflow: 'hidden',
  },
  cardDropdownStoriesSkeletonContainerBlue: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    height: 168,
    overflow: 'hidden',
    backgroundColor: BLUE,
  },
  cardDropdownStoriesSkeletonOptionContainer: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardDropdownStoriesSkeletonOptionContainerBlue: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: BLUE,
  },
  cardDropdownStoriesContainer: {marginBottom: 20, marginRight: 20},
});

export const CardVariant: CardStyleVariant = {
  primary: {
    colorCardContainer: {backgroundColor: WHITE},
    colorCardImageContainer: {backgroundColor: PURPLE_50},
    colorCardTitle: {color: BLUE},
    colorCardOptionContainer: {backgroundColor: WHITE},
    colorCardOptionHeader: {backgroundColor: BLUE, borderBottomColor: WHITE},
    colorCardOptionHeaderTitle: {color: WHITE},
    colorCardItemContainer: {borderBottomColor: GREY_10},
    colorCardItemTitle: {color: BLUE},
    colorCardItemDescription: {color: GREY_BLUE},
    colorCardOptionSkeletonContainer: {borderBottomColor: GREY_10},
    colorCardItemImageContainer: {backgroundColor: PURPLE_50},
    colorCardOptionSkeletonItem: GREY_BLUE_30,
    colorCardOptionSkeletonHeaderItem: BLUE_80,
    colorCardArrowImageFill: BLUE,
    colorCardImageFill: BLUE,
    colorCardImageOptionFill: BLUE,
  },
  secondary: {
    colorCardContainer: {backgroundColor: BLUE},
    colorCardImageContainer: {backgroundColor: BLUE_80},
    colorCardTitle: {color: WHITE},
    colorCardOptionContainer: {backgroundColor: BLUE},
    colorCardOptionHeader: {backgroundColor: BLUE, borderBottomColor: BLACK},
    colorCardOptionHeaderTitle: {color: WHITE},
    colorCardItemContainer: {borderBottomColor: BLACK},
    colorCardItemTitle: {color: WHITE},
    colorCardItemDescription: {color: GREY_BLUE_50},
    colorCardOptionSkeletonContainer: {borderBottomColor: BLACK},
    colorCardItemImageContainer: {backgroundColor: BLUE_80},
    colorCardOptionSkeletonItem: BLUE_80,
    colorCardOptionSkeletonHeaderItem: BLUE_80,
    colorCardArrowImageFill: WHITE,
    colorCardImageFill: YELLOW,
    colorCardImageOptionFill: WHITE,
  },
  disabledPrimary: {
    colorCardContainer: {backgroundColor: GREY_5},
    colorCardImageContainer: {backgroundColor: GREY_10},
    colorCardTitle: {color: GREY_40},
    colorCardOptionContainer: {},
    colorCardOptionHeader: {},
    colorCardOptionHeaderTitle: {},
    colorCardItemContainer: {},
    colorCardItemTitle: {},
    colorCardItemDescription: {},
    colorCardOptionSkeletonContainer: {},
    colorCardItemImageContainer: {},
    colorCardOptionSkeletonItem: '',
    colorCardOptionSkeletonHeaderItem: '',
    colorCardArrowImageFill: GREY_40,
    colorCardImageFill: GREY_40,
    colorCardImageOptionFill: '',
  },
  disabledSecondary: {
    colorCardContainer: {backgroundColor: BLUE_40},
    colorCardImageContainer: {backgroundColor: BLUE_50},
    colorCardTitle: {color: BLUE_30},
    colorCardOptionContainer: {},
    colorCardOptionHeader: {},
    colorCardOptionHeaderTitle: {},
    colorCardItemContainer: {},
    colorCardItemTitle: {},
    colorCardItemDescription: {},
    colorCardOptionSkeletonContainer: {},
    colorCardItemImageContainer: {},
    colorCardOptionSkeletonItem: '',
    colorCardOptionSkeletonHeaderItem: '',
    colorCardArrowImageFill: BLUE_30,
    colorCardImageFill: BLUE_30,
    colorCardImageOptionFill: '',
  },
};
