import { StyleSheet } from 'react-native';
import {
  NEUTRAL_0,
  NEUTRAL_10,
  NEUTRAL_100,
  NEUTRAL_200,
  NEUTRAL_40,
  NEUTRAL_5,
  PRIMARY_100,
  PRIMARY_30,
  PRIMARY_40,
  PRIMARY_50,
  PRIMARY_700,
  PRIMARY_80,
  QUATERNARY_50,
  SECONDARY_100,
  TERTIARY_100,
  TERTIARY_30,
  TERTIARY_50,
} from '../../../../styles/colors';
import { CardStyleVariant } from './CardDropdown.types';

export const styles = StyleSheet.create({
  cardContainer: {
    width: 272,
    height: 168,
    borderRadius: 16,
    padding: 24,
    paddingRight: 23,
    display: 'flex',
    justifyContent: 'space-between',
  },
  cardImageContainer: {
    width: 68,
    height: 68,
    borderRadius: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImage: {
    width: 40,
    height: 40,
  },
  cardArrowImage: {
    height: 24,
    width: 24,
  },
  arrowContainer: {
    height: 20,
    width: 20,
  },
  cardTitle: {
    fontSize: 22,
    width: 189,
  },
  cardDropdownContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  storiesContainer: {},
  cardOptionContainer: {
    width: 272,
    maxHeight: 442,
    minHeight: 168,
    borderRadius: 16,
    overflow: 'hidden',
    display: 'flex',
  },
  cardOptionHeader: {
    height: 58,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
  },
  cardOptionHeaderSkeletonLeftContainer: {
    flexDirection: 'row',
  },
  cardOptionHeaderTitle: {
    fontWeight: '500',
    fontSize: 16,
    width: 170,
    alignItems: 'center',
    display: 'flex',
  },
  cardOptionHeaderImage: {
    height: 20,
    width: 21,
    marginRight: 12,
  },
  cardOptionHeaderUp: {
    height: 12,
    width: 12,
  },
  cardHeaderLeftPart: {
    display: 'flex',
    flexDirection: 'row',
  },
  cardItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 86,
    borderBottomWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardLastItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0,
    minHeight: 86,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardOneItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 118,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  cardItemImageContainer: {
    width: 46,
    height: 46,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderRadius: 50,
  },
  cardItemImageCenter: {
    width: 24,
    height: 24,
    position: 'absolute',
  },
  cardImageCircle: {
    width: 52,
    height: 52,
  },
  cardItemTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  cardItemDescription: {
    fontSize: 14,
    fontWeight: '500',
  },
  overlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  cardOptionSkeletonContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
  },
  cardOptionSkeletonRightContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginLeft: 12,
  },
  cardOptionSeparation: {
    height: 4,
  },
  cardOptionHeaderImg: {
    width: 24,
    height: 24,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardOptionHeaderImagenSize: {
    width: 24,
    height: 24,
  },
  cardOptionImagenSize: {
    width: 24,
    height: 24,
  },
  cardOptionArrowImage: {
    height: 24,
    width: 24,
  },
  cardItemTextContainer: {
    flex: 1,
  },
  cardOptionArrowContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 21,
  },
  cardDropdownStoriesRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  cardDropdownStoriesSkeletonContainer: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    height: 168,
    overflow: 'hidden',
  },
  cardDropdownStoriesSkeletonContainerBlue: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    height: 168,
    overflow: 'hidden',
    backgroundColor: PRIMARY_100,
  },
  cardDropdownStoriesSkeletonOptionContainer: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardDropdownStoriesSkeletonOptionContainerBlue: {
    marginRight: 20,
    marginBottom: 20,
    width: 276,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: PRIMARY_100,
  },
  cardDropdownStoriesContainer: { marginBottom: 20, marginRight: 20 },
});

export const CardVariant: CardStyleVariant = {
  primary: {
    colorCardContainer: { backgroundColor: NEUTRAL_0 },
    colorCardImageContainer: { backgroundColor: QUATERNARY_50 },
    colorCardTitle: { color: PRIMARY_100 },
    colorCardOptionContainer: { backgroundColor: NEUTRAL_0 },
    colorCardOptionHeader: {
      backgroundColor: PRIMARY_100,
      borderBottomColor: NEUTRAL_0,
    },
    colorCardOptionHeaderTitle: { color: NEUTRAL_0 },
    colorCardItemContainer: { borderBottomColor: NEUTRAL_10 },
    colorCardItemTitle: { color: PRIMARY_100 },
    colorCardItemDescription: { color: TERTIARY_100 },
    colorCardOptionSkeletonContainer: { borderBottomColor: NEUTRAL_10 },
    colorCardItemImageContainer: { backgroundColor: QUATERNARY_50 },
    colorCardOptionSkeletonItem: TERTIARY_30,
    colorCardOptionSkeletonHeaderItem: PRIMARY_80,
    colorCardArrowImageFill: PRIMARY_100,
    colorCardImageFill: PRIMARY_100,
    colorCardImageOptionFill: PRIMARY_100,
  },
  secondary: {
    colorCardContainer: { backgroundColor: PRIMARY_100 },
    colorCardImageContainer: { backgroundColor: PRIMARY_80 },
    colorCardTitle: { color: NEUTRAL_0 },
    colorCardOptionContainer: { backgroundColor: PRIMARY_100 },
    colorCardOptionHeader: {
      backgroundColor: PRIMARY_100,
      borderBottomColor: NEUTRAL_100,
    },
    colorCardOptionHeaderTitle: { color: NEUTRAL_0 },
    colorCardItemContainer: { borderBottomColor: NEUTRAL_100 },
    colorCardItemTitle: { color: NEUTRAL_0 },
    colorCardItemDescription: { color: TERTIARY_50 },
    colorCardOptionSkeletonContainer: { borderBottomColor: NEUTRAL_100 },
    colorCardItemImageContainer: { backgroundColor: PRIMARY_80 },
    colorCardOptionSkeletonItem: PRIMARY_80,
    colorCardOptionSkeletonHeaderItem: PRIMARY_80,
    colorCardArrowImageFill: NEUTRAL_0,
    colorCardImageFill: SECONDARY_100,
    colorCardImageOptionFill: NEUTRAL_0,
  },
  disabledPrimary: {
    colorCardContainer: { backgroundColor: NEUTRAL_5 },
    colorCardImageContainer: { backgroundColor: NEUTRAL_10 },
    colorCardTitle: { color: NEUTRAL_40 },
    colorCardOptionContainer: {},
    colorCardOptionHeader: {},
    colorCardOptionHeaderTitle: {},
    colorCardItemContainer: {},
    colorCardItemTitle: {},
    colorCardItemDescription: {},
    colorCardOptionSkeletonContainer: {},
    colorCardItemImageContainer: {},
    colorCardOptionSkeletonItem: NEUTRAL_200,
    colorCardOptionSkeletonHeaderItem: NEUTRAL_200,
    colorCardArrowImageFill: NEUTRAL_40,
    colorCardImageFill: NEUTRAL_40,
    colorCardImageOptionFill: '',
  },
  disabledSecondary: {
    colorCardContainer: { backgroundColor: PRIMARY_40 },
    colorCardImageContainer: { backgroundColor: PRIMARY_50 },
    colorCardTitle: { color: PRIMARY_30 },
    colorCardOptionContainer: {},
    colorCardOptionHeader: {},
    colorCardOptionHeaderTitle: {},
    colorCardItemContainer: {},
    colorCardItemTitle: {},
    colorCardItemDescription: {},
    colorCardOptionSkeletonContainer: {},
    colorCardItemImageContainer: {},
    colorCardOptionSkeletonItem: PRIMARY_700,
    colorCardOptionSkeletonHeaderItem: PRIMARY_700,
    colorCardArrowImageFill: PRIMARY_30,
    colorCardImageFill: PRIMARY_30,
    colorCardImageOptionFill: '',
  },
};
